### ISSUE TITLE
Shortcut for setting active window/tab (cmd+F8) doesn't work

### ISSUE THREAD

**Issue by MaxEisner** [beardedspice/beardedspice#168]
if i try to set a window active using the shortcut, it won't work. if i try to set up the shortcut again, it doesn't recognizes the F8 button...

**Comment by foozee** [comment]
in the current release (1.0.8 at this time) those shortcuts are not set
by-default yet, but you can set them yourself by going to Bearderspice
preferences, under `shortcuts` tab there is a shortcut for `set active
plater window`

please note that to set something to F8 you actually need to press the fn
key on the keyboard, otherwise you're setting it to `cmd` + `play` which
isn't supported by BS
