### ISSUE TITLE
[Feature Suggestion] Support for headphone controls

### ISSUE THREAD

**Issue by jzw95** [beardedspice/beardedspice#209]
I love BeardedSpice, so first of all thanks for your great work! My one issue is that it doesn't support the controls on headphones which can normally be used instead of the media keys when attached to the Mac. I often reach for those as they are nearby and end up starting iTunes instead of pausing SoundCloud (my most common use of BeardedSpice)! Any chance the headphone remote events could also be intercepted by BeardedSpice? Thanks!

**Comment by micros123** [comment]
Exactly the same thanks and problem here :-) When I press play on my plugged in headphones it still triggers iTunes instead of Spotify. The play/pause on the keyboard is working fine now with BeardedSpice on El Capitan.

**Comment by Stillness-2** [comment]
Describe the problem more detailed, please. For example, spotify web client or spotify app, which "player" is active in Beardedspice. And so on...

**Comment by micros123** [comment]
Ok:
**Initial problem:** Since upgrading to El Capitan all media keys (keyboard play/pause and play/pause on plugged-in headphone with remote buttons in the cable) trigger iTunes instead of other media players.
**Current situation:** I installed BeardedSpice and it worked out of the box for my keyboard. It now controls the Spotify standalone application when I hit play/pause on my OSX keyboard. However, clicking the play/pause button on the plugged-in apple headphones still trigger iTunes and does not affect BeardedSpice or Spotify.
**Desired situation:** The play/pause button of the plugged-in headphones should behave just as the play/pause button on the keyboard: Sending the signal via BeardedSpice to Spotify instead of triggering iTunes natively.
Hope this clears things up?

**Comment by jzw95** [comment]
I have found that the latest 1.2 sort of enables my headphone controls (Sennheiser PX200-IIi) with SoundCloud's website, but it's buggy. I can start tracks. I can usually pause them. But frequently when I pause the track, it pauses SoundCloud, switches the Active Player Window to iTunes, and unpauses iTunes. Also, while playing SoundCloud, when double-clicking the headphone control to skip forward a track, SoundCloud moves to the next track and starts playing it as expected, but iTunes also moves to the next track (though remains paused).

**Comment by Stillness-2** [comment]
It is very strange. Can you try this build: https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1

**Comment by jzw95** [comment]
In the last hour and a bit, the build you link to above has been working reliably with my headphone controls. Thanks!
