### ISSUE TITLE
Not showing any of the track including iTunes, youtube etc

### ISSUE THREAD

**Issue by vighneshpai** [beardedspice/beardedspice#446]
Using it on latest Mac OS 10.11.5

I don't know whats problem? But I've used this on my same MacBook previously!

**Comment by 1ps0** [comment]
What version are you using? 
Also how many tabs/windows do you have open? If you try with a small number of tabs/windows open does it work?

**Comment by rjcragg** [comment]
I've got a similar issue. Mac OS 10.11.16. YouTube pages in Safari used to be shown, but are not longer shown. Been a few months since this happened.

In Chrome, some pages are shown, but some are not. 
https://www.youtube.com/watch?v=lo6x4eulY9g gets shown
https://www.youtube.com/watch?v=Y9Us4QH7JbY is not shown

**Comment by 1ps0** [comment]
Did you check against [this issue](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later))?

**Comment by 1ps0** [comment]
Closing this as a known and user-resolved issue. Please re-open if the given solution doesn't work.
