### ISSUE TITLE
Plex pause button broke.  

### ISSUE THREAD

**Issue by bcomnes** [beardedspice/beardedspice#457]
The pause button no longer pauses or plays tracks.  Skipping tracks still works.  Maybe the selector needs updating?  

Chrome and Safari.  OSX 10.11.6. BS 2.0.0 Plex Web Plugin v.2

**Comment by bcomnes** [comment]
Looks like https://github.com/beardedspice/beardedspice/pull/450 might be a fix.

**Comment by 1ps0** [comment]
Since you're using this strategy and I don't currently have a PLEX setup. Can you test that PR real quick? (#405). You can download the file [here](https://raw.githubusercontent.com/askedrelic/beardedspice/326f302ab154bd298f380e868c71b296c1bfdffe/BeardedSpice/MediaStrategies/PlexWeb.js) and import it from preferences.

**Comment by bcomnes** [comment]
It doesn't quite fix it, but I'm getting the hang of how to make edits myself to strategies.  I'll poke at it.

**Comment by bcomnes** [comment]
Sent a PR into the existing PR to fix it.  https://github.com/askedrelic/beardedspice/pull/1

**Comment by askedrelic** [comment]
hey @bcomnes this was fixed with #450 right?

**Comment by bcomnes** [comment]
Nailed it!  Auto updated, and pausing great
