### ISSUE TITLE
Privacy concern

### ISSUE THREAD

**Issue by xyzzyx11** [beardedspice/beardedspice#505]
How can you be sure that when you allow bearded spice access to the keyboard, it doesn't see every single key you type?

**Comment by 1ps0** [comment]
Its registered on a per-key basis. Nice thing about open source software is you can read what and where it does all the things, and if you're still not convinced, you can compile and run it yourself. 

In this case we only bind for events made by keys we/you specify as the shortcuts to use.

Plus, manual updates aside, we don't do any kind of network or analytics transactions from the app. The github.io site has ganalytics embedded, otherwise everything is manual and explicit. Check for program updates, check for web strategy updates. And the strategies are relatively easy to read, without diving into the program code itself.

**Comment by 1ps0** [comment]
After three+ months, I'm considering this closed. If there's further discussion needed just respond and we can go deeper if you'd like. I would ask you read the code first if you have any deeper concerns. Seeing it done and reading API documentation can answer most questions. 
Most/all relevant concerns for the app itself are straightforwardly answered in the code itself.
