### ISSUE TITLE
Safari 10.0.1 and Beardedspice 2.1.5

### ISSUE THREAD

**Issue by grafiprints** [beardedspice/beardedspice#540]
Hello,
Beardedspice won't detect any tabs on safari (10.0.1) osx 10.12.1, even after enabling the allow Javascript from Apple Events option (Flash is enabled on soundcloud page).

[
![screen shot 2016-12-16 at 16 12 16](https://cloud.githubusercontent.com/assets/8658093/21265604/f2bd21a0-c3aa-11e6-9251-0444df4cf076.png)
](url)

**Comment by AnthonyWhitakerJr** [comment]
Latest version is 2.1.**2**
Just tested SoundCloud with version 2.1.2, unable to reproduce.
Did restart BeardedSpice after enabling it in Security & Privacy / Accessibility?

<img width="1043" alt="screen shot 2016-12-16 at 2 29 43 pm" src="https://cloud.githubusercontent.com/assets/5818070/21275758/4f3adfbc-c39c-11e6-9d31-75f93812c590.png">

**Comment by 1ps0** [comment]
We've seen this a little bit recently, with #525 and #524. 

Try removing the app entirely and installing from scratch.

**Comment by etataurov** [comment]
Hello! Thanks!
I also had a problem with this version of Safari. reinstalling didn't help me,
but allowing Javascript from Apple Events helped.
There is a message about it on the wiki https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)
But I think README.md should contain that info too, in more explicit form, because it's crucial for Safari support

**Comment by 1ps0** [comment]
@grafiprints Are you still seeing this issue?

**Comment by clayton-grey** [comment]
For what it's worth, I had to enable the Apple Events thing in 10.0.2 on a fresh installation on a new Mac Book Pro. Initially that didn't work. I had to reinstall. On reinstallation, it worked, but only with the developer Apple Events flag on.

**Comment by 1ps0** [comment]
Closing this for lack of response for OP. Assuming resolved :)
