### ISSUE TITLE
[Prerelease] v2.2.0 beta - Mega thread

### ISSUE THREAD

**Issue by 1ps0** [beardedspice/beardedspice#549]
For the new prerelease build (current `beta 1`) found **[here](https://github.com/beardedspice/beardedspice/releases/tag/v2.2.0-b1)**.

Please put any issues, concerns, or commentary here.

**Comment by choco** [comment]
Just wanted to report that it doesn't recognize Safari Technology Preview tabs for me :(

**Comment by 1ps0** [comment]
@choco Are you sure you're running the Technology Preview? I just installed `10.0.3` for El Capitan and the identifier is the same as normal Safari (`com.apple.Safari`).

Easy checks: 
- Is the app name different? (SafariTechPreview.app vs Safari.app, etc).
- If you open your Safari app's contained files (right click and 'Show Package Contents') and look in `Contents/Info.plist`. It should have an identifier in it akin to the one above or different. The tech preview compatibility added in this prerelease looks for `com.apple.Safari` or `com.apple.SafariTechnologyPreview`.

**Comment by choco** [comment]
The issue is that the tag isn't getting returned here https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/Tabs/TabAdapter.m#L110 . Javascript is executed but the return statement doesn't return anything :(

Here's a simple test case to run in the Script Editor:
``` applescript
tell application "Safari"
	set theScript to "(function(){ window.X_BeardedSpice_UUID = 'test';})();(function(){return (window.X_BeardedSpice_UUID == undefined ? '': window.X_BeardedSpice_UUID);})();"
	do JavaScript theScript in current tab of first window
end tell
```
change Safari to Safari Technology Preview and it doesn't work (doesn't return the `test` string)
I'm using latest Safari Technology Preview on Sierra. This is probably an issue on apple side :/

**Comment by 1ps0** [comment]
The test script helps a lot. Looks like I'm going to have to actually upgrade to Sierra to test properly. Bear with me while I catch up.

**Comment by choco** [comment]
Just wanted to report that as of the latest Safari Technology Preview release (22) the bug above has been fixed and Beardedspice works perfectly :)

**Comment by 1ps0** [comment]
Closing this as the period for 2.2.0-b1 preview has passed. Thanks for all your testing and validations :)
