### ISSUE TITLE
Support for Slacker and Sirius XM

### ISSUE THREAD

**Issue by jimdough** [beardedspice/beardedspice#6]
It would be awesome to be able to control Slacker's web player and Sirius XMs

**Comment by mjgorman** [comment]
@josefalcon SiriusXM has recently completely overhauled their site.  Wondering if it would be possible to accomplish now. I can assist if you need anything looked into related to the player, just let me know what you need.

**Comment by foozee** [comment]
@mjgorman Hi, Mahmoud here, currently co-maintaining BS :)  ... I've checked www.siriusxm.com and, yes, they have a new modern interface, and theoritically we can now easily write a BS strategy easily for it :) please [open a new ticket]() for that, if you are also able to expedit the proccess by wiriting the strategy yourself and make a pull request this will be amazing too :) otherwise, just open the ticket and we'll get it done when it's time comes as we work through the issue queue ;)
