### ISSUE TITLE
[Feature Request] Pause playing in background track when new player starts

### ISSUE THREAD

**Issue by voqse** [beardedspice/beardedspice#626]
It'll be nice feature to pause playing track in background when user starts a new one on any supported player. It's also great to continue paused track when the new is stopped.

Thank you!

**Comment by Stillness-2** [comment]
If you mean mouse click on play button, at this moment, it is technically impossible. Maybe when we will make browser extensions. But I don't know exactly...

**Comment by jacklightbody** [comment]
Try [this](https://github.com/kyleneideck/BackgroundMusic) app, it does just what you want and seems to work in conjunction with bearded spice.

**Comment by ndbroadbent** [comment]
Thanks so much for linking to the BackgroundMusic app! I was just about to create a new issue to request this feature. BeardedSpice has been awesome, but the transition between Spotify => YouTube video doesn't work very well. (Spotify keeps playing over the video, then pressing the "pause" key pauses both Spotify and the video, then I have to unpause the video.)

Sorry to comment on such an old issue. But this is the only issue I had with BeardedSpice, so I'm glad I could find a great workaround.

**Comment by ndbroadbent** [comment]
Update: After trying out BackgroundMusic for a few days, I've noticed some annoying edge cases. It works great most of the time, but it looks like it just uses the audio signal to detect sound, and it can't tell if a video has been stopped, or just paused.

It works great if I'm just watching a short YouTube video. But if I start playing a longer mix (e.g. a few hours), and then I pause the music, BackgroundMusic will start playing Spotify again. So then I have to manually pause Spotify, which is annoying.

It would be great if this a built-in feature for BeardedSpice, because it's much smarter and knows if something has been paused vs. stopped.

Another workaround might be if BackgroundMusic could *only* pause music, but not to start playing it again automatically. I think I'd be happy with that.
