### ISSUE TITLE
Safari - unable to enable "Allow JavaScript from Apple Events"

### ISSUE THREAD

**Issue by patrickrushton** [beardedspice/beardedspice#708]
I'm not sure if this is directly related to BeardedSpice, but as of this morning the "Allow JavaScript from Apple Events" in Safari's Develop menu has disabled itself causing it to no longer work with BeardedSprice.

When I try to reenable it by selecting the "Allow JavaScript from Apple Events" menu option, I get the prompt "Are you sure you want to allow JavaScript from Apple Events?". After clicking "Allow", nothing happens. I don't see the prompt to enter admin credentials and the Safari menu item remains unchecked.

I've tried deleting Safari's plist file and disabling all extensions, but still the behaviour is the same.

Is anyone else experiencing this?

**Comment by patrickrushton** [comment]
Alright, this resolved itself overnight (even though previous reboots didn't help).

**Comment by cwagner22** [comment]
I have been having the same issue for the past few months... Any idea what did you do to fix the issue?

**Comment by fotmasta** [comment]
Shoot! This just happened to me on 10.12.6. 
I tried new user account, beta version of Safari, Safari Tech Preview, 
restarts, nuked safari cache, prefs, and that menu item will **not activate for all the tea in China!**

**Comment by mzru** [comment]
Hey All,

I was struggling with this on two separate machines for a couple days via remote desktop. I'd check the option and it wouldn't save.

 I tried updating via terminal via the below instructions and confirming that it had saved and this was still not showing as checked in Safari.

https://stackoverflow.com/questions/37802673/allow-javascript-from-apple-events-in-safari-through-terminal-mac

I ended up reinstalling the OS to see if it would fix it or not. After it finished I went to check the box.... and it worked. On machine two, I had a sneaking suspicion so I tried plugging in instead of doing it via remote desktop instead of going through the whole process of reinstalling and it worked no problem. Immediately prompted for admin password as expected.

Hope it helps!

**Comment by Rekemot** [comment]
I have the same problem with macOS High Sierra, Safari 11.1.1.

I tried different tricks for a few days and finally one worked:
Select the "Allow JavaScript from Apple Events" from Develop menu option in Safari as normal.
When You get the prompt "Are you sure you want to allow JavaScript from Apple Events?" don't click "Allow" with mouse, but press space bar (press this button by keyboard) and and then a magic window asking for a password will appear. 

:-)

**Comment by kccricket** [comment]
@Rekemot's solution fixes the issue with Safari. If you haven't already, you'll need to open `System Preferences > Keyboard > Shortcuts` and change the Full Keyboard Access setting to `All controls`.

**Comment by stubar** [comment]
@Rekemot's solution worked for me also.  What a weird ass Apple bug!!

**Comment by zzz2836** [comment]
This just happened to me too. I did all the above and nothing worked except... Remote Access. I was trying to do this via VNC. After I went to the keyboard and clicked on the "Allow" directly, Safari asked for my password and "Allow JavaScript from Apple Events" was checked! Yay!

This computer is running an older OS, X.12.x.

Back during the ~X.10 or 11 or 12 days, Apple had made a change to the operating system that you could NOT enter an Admin password via a remote connection. It really messed with me and my 40 or so remote computers. I put in a bug/feature/change request and it disappeared almost immediately in the next OS update. I suspect that this Safari issue left over or missed change from back then. At least I got my JavaScript via Apple Events back!
