### ISSUE TITLE
Could we please get an update about this project's current support level?

### ISSUE THREAD

**Issue by Arro** [beardedspice/beardedspice#899]
I happen to use Pocket Casts for my podcasts.  About 2 months ago, it stopped working, because they changed some underlying class names.  Yes, there is a submitted PR which attempts to rectify this.  

In the past, some maintainer of this project would periodically pull in recent PRs and push out a new version.  This hasn't happened in a while, and a bunch of things I use are broken.  

I'm happy to volunteer myself as a maintainer here if the regular contributors are giving up on the project.  

Please, update us.

**Comment by Ido-PX** [comment]
Perhaps one of the forks could take over the project unofficially...

**Comment by 1ps0** [comment]
Apologies for the declined state of things.

I had to step down as a maintainer, especially as my life hit a lot of hard turns. Unfortunately I dont have the ability to add new maintainers.

PRs take a lot of effort to validate, and should be merged carefully because every merge gets pushed out to every active version of the application out there. Thats not a small responsibility. 

For every new site that was added I had to go down a checklist, validate the JS by hand, make or renew a membership in the site (which often wasn't in a language I spoke or in a country I could access, or worse simply couldn't pay for). 

Dead code in a PR strategy is worse than none at all. It slows down the app, and every new strategy adds a subjective amount of time every refresh. Every button push triggers a refresh too. 

At this point it seems like the play/pause ability has been standardized in Chrome and will probably be standard in other browsers this app cant access (such as Firefox). I'd suggest investigating those and/or urging your favorite site to support this new capability. (Sorry, best I can find in reference is [here](https://www.reddit.com/r/chrome/comments/bnqgq6/chrome_support_keyboards_play_and_pause_buttons/).) 

A final word, if you want to keep the system going, the strategies in the PRs can be downloaded and explicitly imported into the app. There is a piece of JS in the app that isnt changable (without recompiling it) that seems subject to being knocked around by Chrome and Safari, but otherwise I see the Issues and PRs here as a form of community when I nor the other maintainers are able to pony up the free time any longer.

**Comment by Tylermarques** [comment]
@1ps0 Can we have a call for new maintainers then? I use this tool daily and would love to have it up and running for Catalina again, but seeing as the last efforts for this project were almost 1.5 years ago, it'd be nice if we could get it updated and maintained again.

**Comment by Stillness-2** [comment]
@Arro @1ps0 @Tylermarques @Ido-PX @nelsonjchen 

#### Support of strategies.

@1ps0 writes everything correctly, support requires times, the fact is that when I still aproved the PR with the strategies, that something was constantly wrong, right PR came extremely rarely. Usually, people don’t bother to check: in all supported browsers, at least in 2 system languages, check the `pause` method. This is so, the problems at a glance ...

My suggestion for today is this - a separate repository, with strategies in the form of strategy files.

Take a look please: [https://github.com/beardedspice/BS-Strategies](https://github.com/beardedspice/BS-Strategies)

#### My participation in supporting the entire project.

A few years ago :) I was concerned about the performance problem when a lot of tabs are open in the browser. The solution that I approved for myself is to use the possibility of browser extensions, as a mechanism for communicating with BeardedSpice. 

This path was thorny, the combination of my laziness with the unreasonability of the Apple (when they changed the concept of extensions in Safari). 

At this stage, I was able to return to implementation. But I realized that the result is something else. Another Beardie :), with its limitations: you need to install extensions in the browser, OS version at least 10.14.

 I decided to fork this into a [separate repository](https://github.com/Stillness-2/beardie). Accordingly, I will spend maximum effort in my free time on this direction. :)

#### New maintainers.

If there are any one, then I will add two :). 

If the repository with unsupported strategies is a good idea :), the first thing that is desirable to do, to move there new (updated) strategies from pull requests.

**Comment by skywinder** [comment]
@Stillness-2 sounds great. Please open issues in your fork. It would also be nice to know about your status update. (as option - just create PR from your working branch to this repo, so we can see changes hostory easily)

 As I can see the latest commit was Nov 21, 2019

**Comment by skywinder** [comment]
cc @1ps0 is there an option to add @Stillness-2  as maintainer of this repo? It's a sad, when we have to make forks from awesome repo. keep it going!

**Comment by Arro** [comment]
I'm going to close this issue as I feel the question has been answered.

**Comment by abrambailey** [comment]
After giving up on getting beardedspice working, I used claude code to create a working solution for chrome and my mac.. it's limited to just bandcamp and youtube in chrome for now, and the spotify app... but hoping to get some others involved in making it better. The workaround I found was pairing it with a chrome extension to get the media keys working... Maybe a silly hack, but would love to hear from more experienced programmers on what could be done better... https://github.com/abrambailey/MediaKeyControls
