### ISSUE TITLE
Add support for desktop Progressive Web Apps

### ISSUE THREAD

**Issue by remi2j** [beardedspice/beardedspice#912]
Chrome recently added support for PWAs, so we can install them as native Mac apps.

The Spotify PWA is [really good](https://twitter.com/ow/status/1111271183503233024)

But the media keys don't seem to work with a PWA, at least on MacOS. Could that be fixed ?

**Comment by remi2j** [comment]
Apparently this is fixed now. Closing

**Comment by mattroark** [comment]
@remidej I'm on Mac OS Catalina 10.15.7 using Chrome 87.0.4280.141 and media controls don't appear to function with PWAs – whether it be Spotify or YouTube Music, for example. Do you know which PR this was addressed with? Or, how you managed to get it working otherwise?

As pointed out in #805 and #818, I have the following option checked – `View > Developer > Allow Javascript from Apple Events`.
