### ISSUE TITLE
[app-support] Spotify (Native)

### ISSUE THREAD

**Issue by haneefmubarak** [beardedspice/beardedspice#94]
It'd be nice if we could still be able to use native apps like Spotify and just switch using `beardedspice`. I think we could use AppleScript or something, but I don't do enough OSX work to know.

Could that work?

Also see #95.

**Comment by dslysenko** [comment]
So now that #29 has been solved in #122, isn't this up for re-opening since BeardedSpice will grab mediakeys focus aggressively thus removing it from Spotify?

I did a proof-of-concept (read: poorly worked) implementation of Spotify integration in a few hours by simply duplicating & modifying the iTunes code to work with the interface declared in this gist:

https://gist.github.com/dslysenko/fcc65bcf24c94af82a47

**Comment by dslysenko** [comment]
@Stillness-2

**Comment by nadavoosh** [comment]
Hey everyone. Enjoying beardedspice, nice work! I wanted to note that I have this issue too.

**Comment by bredman** [comment]
I would also vote for this, right now I can't use beardedspice and the native spotify app at the same time.

**Comment by dslysenko** [comment]
@Stillness-2 feel free to use if any of this helps: (different from the other gist I posted) https://gist.github.com/dslysenko/6a7ff957f1ed2f7ca6f5

**Comment by snipem** [comment]
Maybe slightly off topic this wonders me:

How is the media key bound to a application? Is there a way to force an application not to block the media key. Whenever Spotify or BeardedSpice isn't used, iTunes pops up as soon as I push the media key. How is this controlled and can it be enforced by BeardedSpice?

**Comment by Stillness-2** [comment]
We are working on it

**Comment by Stillness-2** [comment]
Done. Unfortunately, BeardedSpice not supports setting of favorite for Spotify.
