### ISSUE TITLE
[App Support] Firefox

### ISSUE THREAD

**Issue by ajs256** [beardedspice/beardedspice#942]
I want to start by saying that I really love BeardedSpice. It has been so useful to me!

I would like support for sites in Firefox. If someone could add it, that would be great!

**Comment by Hlaxfors** [comment]
Yes please, I feel like many people who would use BeardedSpice will be the kind to use firefox!

**Comment by Etrit1** [comment]
I 3rd say yes please to Firefox Support.

Safari outright sucks as a program
Chrome is eeeh, ok but; I depend on some addons that it doesn't have. 

Also, Hlaxfors is right, Firefox users frequently end up being more of wanting a custom interface type of people.   BeardedSpice is totally custom interfacy! ;-)

And it looks like a GREAT program.  Just please please firefox support.

**Comment by Etrit1** [comment]
Soo, I did some more research on Firefox and shortcut keys to control videos from Youtube with keyboard shortcuts.

Apparently, the ONLY way you can use keyboard shortcut keys to control anything going on in a tab on Firefox is IF Firefox is the active application.  Which is why BeardedSpice doesn't support Firefox.  It's nothing Spice can fix.
--Booo

I found this extension:  

https://addons.mozilla.org/en-US/firefox/addon/media-keys/

That at least gives you Play/Pause via a keyboard media keys on your keyboard
It doesn't work on Mac (which I'm on)... because Apple sucks and has a tight control over the media keys and they open Music/Itunes.

Again, you have to have Firefox active even on Windows.  (or linux)

Youtube Control Center is pretty good if you just want Youtube to live in your Firefox Toolbar so you atleast don't have to try to find the Youtube tap to play/pause if you're just listening to music..or to skip tracks even.

**Comment by Hlaxfors** [comment]
Hey I discovered that this feature is actually in Firefox already, just, not activated for whatever reason.
Its a switch in `about:config` called `media.hardwaremediakeys.enabled`
It allows you to control _meda_ using the _hardware media keys_
**And** it works no matter what application is in focus.
I'm on Mac btw and activating this feature actually disables automatically opening itunes just like spotify does when its open.

**Comment by 1ps0** [comment]
@Hlaxfors can you put something in the wiki about that :)

**Comment by Hlaxfors** [comment]
> @Hlaxfors can you put something in the wiki about that :)

Sure, never done this before so bear with me! :D

**Comment by ajs256** [comment]
I'm closing this now that it's documented - big thanks to @Hlaxfors :)

**Comment by yohannes** [comment]
Hi guys, is there additional step I need to do to have BS detects the Firefox's tab that's playing the media content? I've set `media.hardwaremediakeys.enabled` to true, restarted FF (v79), have youtube content plays in one of the tabs, but BS doesn't detect any opened applicable tab. Any advice?

**Comment by ajs256** [comment]
@yohannes This system is independent of BS. Setting `dom.media.mediasession.enabled` to true (again in about:config) may work, but I'm not sure if BS checks for that API.
