### ISSUE TITLE
[App Support] Microsoft Teams

### ISSUE THREAD

**Issue by Benjamin-K** [beardedspice/beardedspice#967]
I would really appreciate having Microsoft Teams added to the list of supported apps. I know, that it's not a music app, but it would help a lot in working environments as the ringing sound is controlled by the media controls and so music continuous to play instead. Therefore i would be really happy to be able to disable media controls for Microsoft Teams.

**Comment by BartmanEH** [comment]
Doesn't this happen by default because Teams is NOT a supported app? I'm testing this right now. My issue was that every thing is working fine--keyboard controls are controlling music player as expected--until a Teams call comes in, upon which after hanging up, the keyboard controls are hijacked by Teams and just play/pause the ring tone! But now with BeardedSpice, the keyboard controls should stay locked to the media player and play/pause keyboard key should control media player even after a Teams calls. As I said, I'm just starting to test this behaviour. P.S. I do wish BeardedSpice was a black icon in the tray and not white ;-)

**Comment by Benjamin-K** [comment]
You're right, seems to work without further changes. I'll close this. Thanks
